/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoadministracionarticulos;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.io.IOException;
import java.nio.file.Files;        
import java.nio.file.Path;         
import java.nio.file.Paths;        
import java.nio.file.StandardCopyOption; 
import java.util.logging.Level;
/** 
 * Interfaz grafica del programa 
 * @author Miguel Figueroa, Samir Nassar
 */
public class GUI extends javax.swing.JFrame {
    
    private AdministradorArticulos administrador; 
    private String rutaCarpetaInvestigaciones; 
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI.class.getName());

    /**
     * Constructor de la interfaz 
     */
   public GUI() {
        initComponents();
        this.administrador = new AdministradorArticulos(101);
        this.setLocationRelativeTo(null);
        String rutaBaseProyecto = System.getProperty("user.dir"); 
        this.rutaCarpetaInvestigaciones = rutaBaseProyecto + File.separator + "investigaciones";
        
        String rutaCarpetaInvestigaciones = rutaBaseProyecto + File.separator + "investigaciones"; 
        int articulosCargados = administrador.cargarArticulosDesdeCarpeta(rutaCarpetaInvestigaciones);
        if (articulosCargados > 0) {
            JOptionPane.showMessageDialog(this, "Se cargaron " + articulosCargados + " artículos al inicio.", "Carga Exitosa", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se cargó ningún artículo al inicio. Verifique la carpeta 'investigaciones' y el formato de los archivos.", "Advertencia de Carga", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        BotonAnalizarResumen = new javax.swing.JButton();
        BotonAgregarResumen = new javax.swing.JButton();
        BusquedaPorPalabra = new javax.swing.JButton();
        BusquedaPorAutor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BotonListaPalabrasClaves = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SuperMetroMendeley");

        BotonAnalizarResumen.setText("Analizar Resumen");
        BotonAnalizarResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAnalizarResumenActionPerformed(evt);
            }
        });

        BotonAgregarResumen.setText("Agragar Resumen ");
        BotonAgregarResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarResumenActionPerformed(evt);
            }
        });

        BusquedaPorPalabra.setText("Por Palabras Claves");
        BusquedaPorPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaPorPalabraActionPerformed(evt);
            }
        });

        BusquedaPorAutor.setText("Por Autor");
        BusquedaPorAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaPorAutorActionPerformed(evt);
            }
        });

        jLabel2.setText("Busqueda de Investigaciones:");

        BotonListaPalabrasClaves.setText("Lista de Palabras Claves");
        BotonListaPalabrasClaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListaPalabrasClavesActionPerformed(evt);
            }
        });

        jLabel3.setText("Para la busqueda de Investigaciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonAgregarResumen)
                    .addComponent(BotonAnalizarResumen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonListaPalabrasClaves)
                    .addComponent(BusquedaPorAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(BusquedaPorPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(9, 9, 9))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BusquedaPorAutor)
                    .addComponent(BotonAgregarResumen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BusquedaPorPalabra)
                    .addComponent(BotonAnalizarResumen))
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonListaPalabrasClaves)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** 
     * Logica del boton que da una lista de palabras claves 
     * @param evt 
     */
    private void BotonListaPalabrasClavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListaPalabrasClavesActionPerformed
       Lista<PalabrasClave> palabras = administrador.obtenerTodasLasPalabrasClaveOrdenadas();
       Lista<String> PalabrasString = new Lista<>(); 
       for(int i=0; i<palabras.Tamaño(); i++){
           String palabra = palabras.ObtenerPorIndice(i).getPalabra();
           PalabrasString.Agregar(palabra);
       }
       StringBuilder PalabrasClave = new StringBuilder();
       int contador=0;
       for(int i=0; i<PalabrasString.Tamaño(); i++){ 
           contador ++;
           String palabra = PalabrasString.ObtenerPorIndice(i);
           PalabrasClave.append(contador+"."+palabra);
           PalabrasClave.append("\n");
       }
       javax.swing.JTextArea jTextArea = new javax.swing.JTextArea(PalabrasClave.toString());
       jTextArea.setEditable(false);
       jTextArea.setLineWrap(true);
       jTextArea.setWrapStyleWord(true);
       javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(jTextArea);
       scroll.setPreferredSize(new java.awt.Dimension(400, 300));
       javax.swing.JOptionPane.showMessageDialog(this, scroll,"Palabras Clave de todos los articulos", javax.swing.JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_BotonListaPalabrasClavesActionPerformed
    /** 
     * Logica del boton que permite agregar resumenes al programa 
     * @param evt 
     */
    private void BotonAgregarResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarResumenActionPerformed
                                                         
    JFileChooser selectorArchivos = new JFileChooser();
    selectorArchivos.setDialogTitle("Seleccionar Resumen para Agregar"); 
    selectorArchivos.setFileSelectionMode(JFileChooser.FILES_ONLY);
    
   
    selectorArchivos.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos de Texto (.txt)", "txt"));

    int ventanaBusqueda = selectorArchivos.showOpenDialog(this);
    
    if (ventanaBusqueda == JFileChooser.APPROVE_OPTION){ 
       
        File archivoSeleccionadoOriginal = selectorArchivos.getSelectedFile(); 
        
       
        if (!archivoSeleccionadoOriginal.getName().toLowerCase().endsWith(".txt")){
            JOptionPane.showMessageDialog(this, "Error: Seleccione un archivo de tipo .txt", "Tipo de Archivo Inválido", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Path origenPath = archivoSeleccionadoOriginal.toPath(); 
        Path destinoPath = Paths.get(this.rutaCarpetaInvestigaciones, archivoSeleccionadoOriginal.getName()); 
        try {
            Files.copy(origenPath, destinoPath, StandardCopyOption.REPLACE_EXISTING);
            logger.log(Level.INFO, "Archivo {0} copiado a: {1}", new Object[]{archivoSeleccionadoOriginal.getName(), destinoPath}); 
            boolean confirmacion = administrador.CargarArticuloArchivo(destinoPath.toFile()); 
            if(confirmacion){
                JOptionPane.showMessageDialog(this, "Artículo cargado y guardado en carpeta con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error: Archivo duplicado por título o formato inválido.", "Problema al Cargar", JOptionPane.WARNING_MESSAGE);
                logger.log(Level.WARNING, "No se pudo cargar el artículo desde el archivo {0} (posible duplicado o formato inválido).", archivoSeleccionadoOriginal.getName()); 
            }
        } catch (IOException ex) {
            logger.log(Level.SEVERE, "Error al copiar o leer el archivo {0}: {1}", new Object[]{archivoSeleccionadoOriginal.getName(), ex.getMessage()}); 
            JOptionPane.showMessageDialog(this, "Error al procesar el archivo: " + ex.getMessage(), "Error de E/S", JOptionPane.ERROR_MESSAGE);
        }
   
}
    }//GEN-LAST:event_BotonAgregarResumenActionPerformed
    /** 
     * Logica del boton que muestra el nombre de un resumen seleccionado, sus autores
     * palabras claves (con la cantidad de veces que aparece en el resumen)
     * @param evt 
     */
    private void BotonAnalizarResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAnalizarResumenActionPerformed
            Lista<ArticuloCientifico> ListaArticulos = administrador.obtenerTodosLosArticulos();
            if(ListaArticulos==null||ListaArticulos.esVacio()){
                javax.swing.JOptionPane.showMessageDialog(this,"No hay resumenes cargados para analizar", "Sistema Vacio",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            JFrame ListaResumenes = new JFrame("Lista de Resumenes"); 
            ListaResumenes.setSize(500,500);
            ListaResumenes.setLocationRelativeTo(this);
            javax.swing.DefaultListModel<String> Visual = new javax.swing.DefaultListModel<>();
            for(int i=0; i<ListaArticulos.Tamaño(); i++){
                ArticuloCientifico articulo = ListaArticulos.ObtenerPorIndice(i);
                Visual.addElement(articulo.getTitulo());
            }
            javax.swing.JList<String> JListVisual = new javax.swing.JList<>(Visual);
            JListVisual.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
            JListVisual.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent e){ 
                    if(e.getClickCount()==2){ 
                        int index = JListVisual.getSelectedIndex();
                        if(index!=-1){
                            ArticuloCientifico Seleccionado = ListaArticulos.ObtenerPorIndice(index);
                            StringBuilder analisis = new StringBuilder();
                            analisis.append("TITULO: ").append(Seleccionado.getTitulo()).append("\n\n");
                            analisis.append("AUTORES: ");
                            Lista<String> autores = Seleccionado.getAutores();
                            for(int i=0; i<autores.Tamaño(); i++){ 
                                analisis.append(autores.ObtenerPorIndice(i));
                                if(i<autores.Tamaño()-1){
                                    analisis.append(", ");
                                }    
                            }
                            analisis.append("\n\n");
                            analisis.append("PALABRAS CLAVE: ");
                            analisis.append("\n");
                            Lista<String> palabras = Seleccionado.getPalabrasClave();
                            String Texto = Seleccionado.getResumen().toLowerCase();    
                            for(int x=0; x<palabras.Tamaño();x++){ 
                                String palabra = palabras.ObtenerPorIndice(x).toLowerCase().replace(".",""); 
                                int contador= 0;
                                int IndiceBusqueda=0;
                                while ((IndiceBusqueda = Texto.indexOf(palabra, IndiceBusqueda)) != -1) {
                                    contador++;
                                    IndiceBusqueda += palabra.length();
                                }
                                analisis.append("- ").append(palabra).append(": Aparece ").append(contador).append(" veces\n");   
                            }      
                                javax.swing.JTextArea TextArea = new javax.swing.JTextArea(analisis.toString());
                                TextArea.setEditable(false); 
                                TextArea.setLineWrap(true);
                                TextArea.setWrapStyleWord(true);
                                TextArea.setCaretPosition(0);
                                javax.swing.JScrollPane scrollDetalle = new javax.swing.JScrollPane(TextArea);
                                scrollDetalle.setPreferredSize(new java.awt.Dimension(500, 400));
                                javax.swing.JOptionPane.showMessageDialog(ListaResumenes, scrollDetalle, "Análisis del Resumen", javax.swing.JOptionPane.PLAIN_MESSAGE);
                        } 
                    }
                }
            });
            ListaResumenes.add(new javax.swing.JScrollPane(JListVisual));
            ListaResumenes.setVisible(true);        
    }//GEN-LAST:event_BotonAnalizarResumenActionPerformed
    /** 
     * Logica del boton que te permite ver los articulos de un autor seleccionado
     * @param evt 
     */        
    private void BusquedaPorAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaPorAutorActionPerformed
        Lista<Autor> Autores = administrador.obtenerTodosLosAutoresOrdenados();
    if (Autores == null || Autores.esVacio()) {javax.swing.JOptionPane.showMessageDialog(this, "No hay autores registrados en el sistema", "Sistema Vacio", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    javax.swing.JFrame VentanaSeleccion = new javax.swing.JFrame("Seleccione un Autor");
    VentanaSeleccion.setSize(500, 500);
    VentanaSeleccion.setLocationRelativeTo(this);
    javax.swing.DefaultListModel<String> Visual = new javax.swing.DefaultListModel<>();
    for (int i = 0; i < Autores.Tamaño(); i++) {
        Visual.addElement(Autores.ObtenerPorIndice(i).getNombre());
    }
    javax.swing.JList<String> ListaAutores = new javax.swing.JList<>(Visual);
    ListaAutores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    ListaAutores.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent e) {
            if (e.getClickCount() == 2) {
                String Seleccionado = ListaAutores.getSelectedValue();
                if (Seleccionado != null) {
                    VentanaSeleccion.dispose(); 
                    Lista<ArticuloCientifico> resultados = administrador.buscarArticulosPorAutor(Seleccionado);
                    if (resultados == null || resultados.esVacio()) {
                        javax.swing.JOptionPane.showMessageDialog(null, "El autor seleccionado no tiene articulos asociados", "Sin Articulos", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        return;
                    }
                    javax.swing.JFrame ArticulosAutor = new javax.swing.JFrame("Articulos de: " + Seleccionado);
                    javax.swing.DefaultListModel<String> Visual = new javax.swing.DefaultListModel<>();
                    for (int i = 0; i < resultados.Tamaño(); i++) {
                        Visual.addElement(resultados.ObtenerPorIndice(i).getTitulo());
                    }
                    javax.swing.JList<String> ListaArticulos = new javax.swing.JList<>(Visual);
                    ListaArticulos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                    ListaArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
                        @Override
                        public void mouseClicked(java.awt.event.MouseEvent e) {
                            if (e.getClickCount() == 2) {
                                int index = ListaArticulos.getSelectedIndex();
                                if (index != -1) {                                    
                                    ArticuloCientifico articulo = resultados.ObtenerPorIndice(index); 
                                    StringBuilder info = new StringBuilder();
                                    info.append("TITULO: ").append(articulo.getTitulo()).append("\n\n");
                                    info.append("AUTORES: ").append(articulo.getAutores().toString()).append("\n\n"); 
                                    info.append("RESUMEN:\n").append(articulo.getResumen());
                                    javax.swing.JTextArea area = new javax.swing.JTextArea(info.toString());
                                    area.setLineWrap(true);
                                    area.setWrapStyleWord(true);
                                    area.setEditable(false);
                                    area.setCaretPosition(0); 
                                    javax.swing.JScrollPane scrollDetalle = new javax.swing.JScrollPane(area);
                                    javax.swing.JDialog detalleDialogo = new javax.swing.JDialog(ArticulosAutor, "Detalle de Artículos", true);
                                    detalleDialogo.add(scrollDetalle);
                                    detalleDialogo.setSize(700, 500); 
                                    detalleDialogo.setLocationRelativeTo(ArticulosAutor);
                                    detalleDialogo.setVisible(true);
                                }
                            }
                        }
                    });
                    ArticulosAutor.add(new javax.swing.JScrollPane(ListaArticulos));
                    ArticulosAutor.setSize(500, 400);
                    ArticulosAutor.setLocationRelativeTo(null);
                    ArticulosAutor.setVisible(true);
                }
            }
        }
    });
    VentanaSeleccion.add(new javax.swing.JScrollPane(ListaAutores));
    VentanaSeleccion.setVisible(true);
    }//GEN-LAST:event_BusquedaPorAutorActionPerformed
    /** 
     * Logica del boton que permite ver los articulos asociados a una palabra clave especifica
     * @param evt 
     */
    private void BusquedaPorPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaPorPalabraActionPerformed
        String PalabraClave = JOptionPane.showInputDialog(this,"Escriba la palabra clave");
        if(PalabraClave ==null||PalabraClave.trim().isEmpty()){ 
            return;
        }
        Lista<ArticuloCientifico> resultados = administrador.buscarArticulosPorPalabraClave(PalabraClave.trim());
        if(resultados==null||resultados.esVacio()){ 
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontraron artículos con la palabra clave: \"" + PalabraClave + "\"", "Sin Resultados", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        javax.swing.JFrame VentanaArticulos = new javax.swing.JFrame("Resultados para: " + PalabraClave);
        javax.swing.DefaultListModel<String> Visual = new javax.swing.DefaultListModel<>();
        for(int i=0; i<resultados.Tamaño();i++){ 
            Visual.addElement(resultados.ObtenerPorIndice(i).getTitulo());    
        }
        javax.swing.JList<String> listaVisual = new javax.swing.JList<>(Visual);
        listaVisual.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaVisual.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent e) {
            if (e.getClickCount() == 2) {
                int index = listaVisual.getSelectedIndex();
                if (index != -1) {
                    ArticuloCientifico articulo = resultados.ObtenerPorIndice(index);
                    StringBuilder info = new StringBuilder();
                    info.append("TÍTULO: ").append(articulo.getTitulo()).append("\n\n");
                    info.append("AUTORES: ");
                    Lista<String> autores = articulo.getAutores();
                    for(int k=0; k<autores.Tamaño(); k++){
                        info.append(autores.ObtenerPorIndice(k));
                        if(k < autores.Tamaño()-1) info.append(", ");
                    }
                    info.append("\n\n");
                    info.append("RESUMEN:\n").append(articulo.getResumen());
                    javax.swing.JTextArea area = new javax.swing.JTextArea(info.toString());
                    area.setLineWrap(true);
                    area.setWrapStyleWord(true);
                    area.setEditable(false);
                    area.setCaretPosition(0);
                    javax.swing.JScrollPane scrollDetalle = new javax.swing.JScrollPane(area);
                    javax.swing.JDialog detalleDialogo = new javax.swing.JDialog(VentanaArticulos, "Detalle del Artículo", true);
                    detalleDialogo.add(scrollDetalle); 
                    detalleDialogo.setSize(700, 500); 
                    detalleDialogo.setLocationRelativeTo(VentanaArticulos); 
                    detalleDialogo.setVisible(true);
                }
            }
        }
    });
    javax.swing.JScrollPane scrollPrincipal = new javax.swing.JScrollPane(listaVisual);
    VentanaArticulos.add(scrollPrincipal);
    VentanaArticulos.setSize(500, 500);
    VentanaArticulos.setLocationRelativeTo(this);
    VentanaArticulos.setVisible(true);    
    }//GEN-LAST:event_BusquedaPorPalabraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarResumen;
    private javax.swing.JButton BotonAnalizarResumen;
    private javax.swing.JButton BotonListaPalabrasClaves;
    private javax.swing.JButton BusquedaPorAutor;
    private javax.swing.JButton BusquedaPorPalabra;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}

