/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoadministracionarticulos;

import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author malej
 */
public class GUI extends javax.swing.JFrame {
    
    private AdministradorArticulos administrador; 
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI.class.getName());

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.administrador = new AdministradorArticulos(101);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        BotonAnalizarResumen = new javax.swing.JButton();
        BotonAgregarResumen = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BotonListaPalabrasClaves = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SuperMetroMendeley");

        BotonAnalizarResumen.setText("Analizar Resumen");
        BotonAnalizarResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAnalizarResumenActionPerformed(evt);
            }
        });

        BotonAgregarResumen.setText("Agragar Resumen ");
        BotonAgregarResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarResumenActionPerformed(evt);
            }
        });

        jButton3.setText("Por Palabras Claves");

        jButton4.setText("Por Autor");

        jLabel2.setText("Busqueda de Investigaciones:");

        BotonListaPalabrasClaves.setText("Lista de Palabras Claves");
        BotonListaPalabrasClaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListaPalabrasClavesActionPerformed(evt);
            }
        });

        jLabel3.setText("Para la busqueda de Investigaciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonAgregarResumen)
                    .addComponent(BotonAnalizarResumen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonListaPalabrasClaves)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(9, 9, 9))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(BotonAgregarResumen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(BotonAnalizarResumen))
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonListaPalabrasClaves)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonListaPalabrasClavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListaPalabrasClavesActionPerformed
       Lista<PalabrasClave> palabras = administrador.obtenerTodasLasPalabrasClaveOrdenadas();
       Lista<String> PalabrasString = new Lista<>(); 
       for(int i=0; i<palabras.Tamaño(); i++){
           String palabra = palabras.ObtenerPorIndice(i).getPalabra();
           PalabrasString.Agregar(palabra);
       }
       StringBuilder PalabrasClave = new StringBuilder();
       int contador=0;
       for(int i=0; i<PalabrasString.Tamaño(); i++){ 
           contador ++;
           String palabra = PalabrasString.ObtenerPorIndice(i);
           PalabrasClave.append(contador+"."+palabra);
           PalabrasClave.append("\n");
       }
       javax.swing.JTextArea jTextArea = new javax.swing.JTextArea(PalabrasClave.toString());
       jTextArea.setEditable(false);
       jTextArea.setLineWrap(true);
       jTextArea.setWrapStyleWord(true);
       javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(jTextArea);
       scroll.setPreferredSize(new java.awt.Dimension(400, 300));
       javax.swing.JOptionPane.showMessageDialog(this, scroll,"Palabras Clave de todos los articulos", javax.swing.JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_BotonListaPalabrasClavesActionPerformed

    private void BotonAgregarResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarResumenActionPerformed
        JFileChooser selectorArchivos = new JFileChooser();
        selectorArchivos.setDialogTitle("Seleccionar Resumen");
        selectorArchivos.setFileSelectionMode(JFileChooser.FILES_ONLY);
        selectorArchivos.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int ventanaBusqueda = selectorArchivos.showOpenDialog(this);  
        if (ventanaBusqueda == selectorArchivos.APPROVE_OPTION){
            File archivoSeleccionado = selectorArchivos.getSelectedFile();
               if (!archivoSeleccionado.getName().toLowerCase().endsWith(".txt")){
                   JOptionPane.showMessageDialog(this,"Error", "Su archivo debe ser de tipo .txt",JOptionPane.WARNING_MESSAGE);   
                   return;
                }
            try {
                boolean confirmacion = administrador.CargarArticuloArchivo(archivoSeleccionado);
                if(confirmacion){ 
                    JOptionPane.showMessageDialog(this, "Cargado con éxito");
                }else{ 
                    JOptionPane.showMessageDialog(this, "Error: Archivo duplicado o vacio");
                }
                }catch (Exception ex) { 
                    JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
                }   
        }
    }//GEN-LAST:event_BotonAgregarResumenActionPerformed

    private void BotonAnalizarResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAnalizarResumenActionPerformed
            Lista<ArticuloCientifico> ListaArticulos = administrador.obtenerTodosLosArticulos();
            if(ListaArticulos==null||ListaArticulos.esVacio()){
                javax.swing.JOptionPane.showMessageDialog(this,"No hay resumenes cargados para analizar", "Sistema Vacio",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            JFrame ListaResumenes = new JFrame("Lista de Resumenes"); 
            ListaResumenes.setSize(500,500);
            ListaResumenes.setLocationRelativeTo(this);
            javax.swing.DefaultListModel<String> Visual = new javax.swing.DefaultListModel<>();
            for(int i=0; i<ListaArticulos.Tamaño(); i++){
                ArticuloCientifico articulo = ListaArticulos.ObtenerPorIndice(i);
                Visual.addElement(articulo.getTitulo());
            }
            javax.swing.JList<String> JListVisual = new javax.swing.JList<>(Visual);
            JListVisual.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
            JListVisual.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent e){ 
                    if(e.getClickCount()==2){ 
                        int index = JListVisual.getSelectedIndex();
                        if(index!=-1){
                            ArticuloCientifico Seleccionado = ListaArticulos.ObtenerPorIndice(index);
                            StringBuilder analisis = new StringBuilder();
                            analisis.append("TITULO: ").append(Seleccionado.getTitulo()).append("\n\n");
                            analisis.append("AUTORES: ");
                            Lista<String> autores = Seleccionado.getAutores();
                            for(int i=0; i<autores.Tamaño(); i++){ 
                                analisis.append(autores.ObtenerPorIndice(i));
                                if(i<autores.Tamaño()-1){
                                    analisis.append(", ");
                                }    
                            }
                            analisis.append("\n\n");
                            analisis.append("PALABRAS CLAVE: ");
                            analisis.append("\n");
                            Lista<String> palabras = Seleccionado.getPalabrasClave();
                            String Texto = Seleccionado.getResumen().toLowerCase();    
                            for(int x=0; x<palabras.Tamaño();x++){ 
                                String palabra = palabras.ObtenerPorIndice(x).toLowerCase().replace(".",""); 
                                int contador= 0;
                                int IndiceBusqueda=0;
                                while ((IndiceBusqueda = Texto.indexOf(palabra, IndiceBusqueda)) != -1) {
                                    contador++;
                                    IndiceBusqueda += palabra.length();
                                }
                                analisis.append("- ").append(palabra).append(": Aparece ").append(contador).append(" veces\n");   
                            }      
                                javax.swing.JTextArea TextArea = new javax.swing.JTextArea(analisis.toString());
                                TextArea.setEditable(false); 
                                TextArea.setLineWrap(true);
                                TextArea.setWrapStyleWord(true);
                                TextArea.setCaretPosition(0);
                                javax.swing.JScrollPane scrollDetalle = new javax.swing.JScrollPane(TextArea);
                                scrollDetalle.setPreferredSize(new java.awt.Dimension(500, 400));
                                javax.swing.JOptionPane.showMessageDialog(ListaResumenes, scrollDetalle, "Análisis del Resumen", javax.swing.JOptionPane.PLAIN_MESSAGE);
                        } 
                    }
                }
            });
            ListaResumenes.add(new javax.swing.JScrollPane(JListVisual));
            ListaResumenes.setVisible(true);        
    }//GEN-LAST:event_BotonAnalizarResumenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarResumen;
    private javax.swing.JButton BotonAnalizarResumen;
    private javax.swing.JButton BotonListaPalabrasClaves;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}

